// NOTE: this server is purely a dev-mode server. In production, the
// server/index.js server also serves the API routes.

// Configure process.env with .env.* files
require('./env').configureEnv();

// Log Integration creds presence on boot
console.log('[server] Integration creds present?', {
  INTEGRATION_CLIENT_ID: !!process.env.INTEGRATION_CLIENT_ID,
  INTEGRATION_CLIENT_SECRET: !!process.env.INTEGRATION_CLIENT_SECRET,
});

const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const cors = require('cors');
const apiRouter = require('./apiRouter');
const wellKnownRouter = require('./wellKnownRouter');
const webmanifestResourceRoute = require('./resources/webmanifest');
const robotsTxtRoute = require('./resources/robotsTxt');
const sitemapResourceRoute = require('./resources/sitemap');

const radix = 10;
const PORT = parseInt(process.env.REACT_APP_DEV_API_SERVER_PORT, radix);
const app = express();

// NOTE: CORS is only needed in this dev API server because it's
// running in a different port than the main app.
app.use(
  cors({
    origin: process.env.REACT_APP_MARKETPLACE_ROOT_URL,
    credentials: true,
  })
);
app.use(cookieParser());
app.use(bodyParser.json());

// Attach Integration SDK to app (used by /api/top-lenders and others)
try {
  const { getIntegrationSdk } = require('./api-util/integrationSdk');
  const integrationSdk = getIntegrationSdk();
  if (integrationSdk) {
    app.set('integrationSdk', integrationSdk);
    console.log('✅ [dev] integrationSdk attached to app');
  }
} catch (e) {
  console.warn('⚠️ [dev] integrationSdk not attached:', e && e.message);
}
app.use('/.well-known', wellKnownRouter);
app.use('/api', apiRouter);

// Generate web app manifest
// When developing with "yarn run dev",
// you can reach the manifest from http://localhost:3500/site.webmanifest
// The corresponding <link> element is set in src/components/Page/Page.js
app.get('/site.webmanifest', webmanifestResourceRoute);

// robots.txt and sitemap-* fetches should return similarly compressed data as server/index.js
app.use(compression());

// robots.txt is generated by resources/robotsTxt.js
// It creates the sitemap URL with the correct marketplace URL
app.get('/robots.txt', robotsTxtRoute);

// Handle different sitemap-* resources. E.g. /sitemap-index.xml
app.get('/sitemap-:resource', sitemapResourceRoute);

// Health check endpoints
app.get('/health', (req, res) => {
  res.json({ ok: true });
});
app.get('/healthz', (_req, res) => res.status(204).send());
app.head('/healthz', (_req, res) => res.status(204).send());

const port = process.env.REACT_APP_DEV_API_SERVER_PORT || 3500;
app.listen(port, () => console.log('[server] listening on', port));
